return {}

-- local M = {
--   "stevearc/oil.nvim",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
-- }
--
-- M.opts = {
--   skip_confirm_for_simple_edits = true,
--   view_options = {
--     show_hidden = true,
--   },
--   use_default_keymaps = false,
--
--   keymaps = {
--     ["g?"] = "actions.show_help",
--     ["<CR>"] = "actions.select",
--     ["<C-v>"] = "actions.select_vsplit",
--     ["<C-x>"] = "actions.select_split",
--     ["q"] = "actions.close",
--     ["<C-l>"] = "actions.refresh",
--     ["-"] = "actions.parent",
--     ["_"] = "actions.open_cwd",
--     ["`"] = "actions.cd",
--     ["~"] = "actions.tcd",
--     ["g."] = "actions.toggle_hidden",
--   },
-- }
--
-- function M.config(_, opts)
--   require("oil").setup(opts)
--
--   vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
-- end
--
-- return M
